#!/usr/bin/env python3
"""Regenerate reports/index.html from the freshly produced EDA artifacts.

The dashboard is NOT produced by run_all.py — it is a committed static
artifact — so it must be regenerated by an explicit, data-driven generator
(source of truth = reports/SUMMARY_REPORT.json + reports/tables/*, never
hand-edited numbers). Reads:

  - reports/SUMMARY_REPORT.json   P1/P2/P6 headline numbers
  - reports/tables/*.csv          token budget, claim field coverage
  - reports/figures/              gallery (30 PNGs)
  - reports/figures_interactive/  interactive grid (18 HTML)
  - reports/tables/               tables grid

Usage:
    .venv/bin/python scripts/reports/generate_index.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import importlib.util
import sys
_b = Path(__file__).resolve()
while not (_b / "_bootstrap.py").is_file():
    _b = _b.parent
sys.path.insert(0, str(_b))
from _bootstrap import ROOT  # noqa: E402
REPORT_DIR = ROOT / "reports"


def _fnum(x) -> str:
    return f"{int(x):,}" if float(x) == int(x) else f"{float(x):,.1f}"


def load_summary() -> dict:
    with open(REPORT_DIR / "SUMMARY_REPORT.json") as fh:
        return json.load(fh)


def load_csv(path: str) -> list[dict]:
    import csv
    rows = []
    with open(REPORT_DIR / "tables" / path, newline="") as fh:
        for r in csv.DictReader(fh):
            rows.append(r)
    return rows


def class_counts(summary: dict) -> list[dict]:
    """Ordered class composition (percent + count) for the hero bar."""
    counts = summary["P2"]["imbalance"]["type_counts"]
    total = sum(counts.values())
    order = ["insurance_claim", "contract", "correspondence",
             "merger_agreement", "corporate_record"]
    out = []
    for c in order:
        if c not in counts:
            continue
        out.append({"cls": c, "count": counts[c], "pct": 100 * counts[c] / total})
    return out


def token_budget_findings() -> list[str]:
    rows = load_csv("token_budget_coverage.csv")
    by = {int(r["budget"]): float(r["pct"]) for r in rows}
    bits = []
    for b in (4096, 16384, 32768, 131072):
        if b in by:
            bits.append(f"{by[b]:.0f}% \u2264{b//1024}k")
    return bits


def claim_field_findings() -> int:
    """Count insurance GT fields with a 100% fill rate across all subtypes."""
    import csv
    with open(REPORT_DIR / "tables" / "claim_field_coverage.csv", newline="") as fh:
        raw = list(csv.DictReader(fh))
    if not raw:
        return 0
    # first column is the (unnamed) row index = field name
    cols = [c for c in raw[0] if c.strip() and c not in ("field", "Unnamed: 0")]
    if not cols:
        return 0
    n_full = 0
    for row in raw:
        vals = [float(row[c]) for c in cols if row.get(c, "").strip() not in ("", "nan")]
        if vals and all(v == 1.0 for v in vals):
            n_full += 1
    return n_full


def build_index_html(summary: dict) -> str:
    p1, p2, p6 = summary["P1"], summary["P2"], summary["P6"]
    classes = class_counts(summary)
    total = sum(c["count"] for c in classes)
    strata = p2["imbalance"]["n_strata"]
    imbal = p2["imbalance"]["max_min_imbalance_ratio_type"]
    cuad = p1["cuad_offsets"]
    maud = p1["maud_labels"]
    cj = p1["config_join"]
    token_bits = token_budget_findings()
    n_full_claim = claim_field_findings()
    corr = p6["coverage"]

    # --- hero stats -------------------------------------------------------
    stats = [
        ("Documents", _fnum(total)),
        ("Doc Types", str(len(classes))),
        ("Strata", str(strata)),
        ("Imbalance Ratio", f"{imbal:.1f}\u00d7"),
        ("CUAD Spans", _fnum(cuad["total_spans"])),
        ("Offset Match", f"{100*cuad['match_rate']:.0f}%"),
    ]

    # --- class bar + legend -----------------------------------------------
    bar = "\n".join(
        f'    <div class="{c["cls"]}" style="width:{c["pct"]:.1f}%">{c["pct"]:.1f}%</div>'
        for c in classes
    )
    legend = "\n".join(
        f'    <span class="l-{c["cls"][:3]}">{c["cls"]} &mdash; {_fnum(c["count"])}</span>'
        for c in classes
    )

    # --- key findings (data-driven) ----------------------------------------
    findings = [
        f"Token budget: {'; '.join(token_bits) if token_bits else 'n/a'}",
        (f"CUAD: {_fnum(cuad['rows_with_labels'])} contracts \u00d7 41 clause types; "
         f"{_fnum(cuad['total_spans'])} spans, {100*cuad['match_rate']:.0f}% exact offset"),
        (f"MAUD: {_fnum(maud['rows_with_labels'])} agreements \u00d7 {maud['distinct_tasks']} tasks"),
        f"Insurance: {n_full_claim}/13 fields 100% filled; coverage determination fully populated",
        (f"Correspondence: intent {corr['coverage_pct']:.0f}% hydrated "
         f"({corr['correspondence_rows']} rows; " +
         "; ".join(f"{k} {v}" for k, v in sorted(corr["sources"].items())) + ")"),
        (f"Split: train {_fnum(cj['gt_split_counts']['train'])} / "
         f"test {_fnum(cj['gt_split_counts']['test'])} "
         f"({100*cj['gt_split_counts']['test']/total:.1f}%)"),
    ]
    findings_html = "\n".join(f"      <li>{f}</li>" for f in findings)

    # --- artifact grids ----------------------------------------------------
    figs = sorted(p.name for p in (REPORT_DIR / "figures").glob("*.png"))
    gallery = "\n".join(
        f'    <div class="gallery-item" onclick="openLightbox(this)"><img src="figures/{f}" '
        f'loading="lazy" alt="{f}"><div class="caption">{f[:-4]}</div></div>'
        for f in figs
    )
    inter = sorted(p.name for p in (REPORT_DIR / "figures_interactive").glob("*.html"))
    interactive = "\n".join(
        f'    <div class="interactive-card"><iframe src="figures_interactive/{f}" '
        f'loading="lazy" title="{f[:-5]}"></iframe><div class="ic-caption">{f[:-5]}</div></div>'
        for f in inter
    )
    tables = sorted(p.name for p in (REPORT_DIR / "tables").glob("*"))
    tables = [t for t in tables if t != "README.md"]
    table_cards = "\n".join(
        f'    <a class="table-card" href="tables/{t}"><div class="icon">{"\U0001F4CB" if t.endswith(".json") else "\U0001F4CA"}</div>'
        f'<div class="info"><div class="name">{t}</div><div class="desc">{t}</div></div></a>'
        for t in tables
    )

    generated = "2026-09-13"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Interactive EDA dashboard for the mailroom-dataset (v1 / corpus v9) — {_fnum(total)} legal documents across {len(classes)} classes, {strata} strata.">
<meta property="og:title" content="mailroom-dataset Corpus — EDA Dashboard">
<meta property="og:description" content="Interactive exploration of the canonical legal-document corpus powering the LLM-Mailroom evaluation pipeline.">
<meta property="og:type" content="website">
<title>mailroom-dataset Corpus — EDA Dashboard</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📊</text></svg>">
<style>
  :root {{
    --bg: #0f1117; --surface: #1a1d29; --card: #212433;
    --border: #2a2d3e; --text: #e2e4ed; --muted: #8b8fa3;
    --accent: #6c72ff; --accent2: #38bdf8; --accent3: #f472b6;
    --green: #34d399; --orange: #fb923c; --red: #f87171;
    --radius: 10px;
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:'Inter',system-ui,-apple-system,sans-serif; background:var(--bg); color:var(--text); line-height:1.6; -webkit-font-smoothing:antialiased; }}
  a {{ color:var(--accent2); text-decoration:none; transition:color .15s; }} a:hover {{ color:var(--accent); text-decoration:underline; }}

  /* ── Hero ── */
  .hero {{ background:linear-gradient(135deg,#1a1040 0%,#0f1117 50%,#0a1628 100%); padding:3.5rem 2rem 2.5rem; border-bottom:1px solid var(--border); position:relative; overflow:hidden; }}
  .hero::before {{ content:''; position:absolute; top:-50%; right:-10%; width:400px; height:400px; background:radial-gradient(circle,rgba(108,114,255,.08) 0%,transparent 70%); pointer-events:none; }}
  .hero-inner {{ max-width:1100px; margin:0 auto; position:relative; }}
  .hero h1 {{ font-size:2.4rem; font-weight:700; margin-bottom:0.3rem; letter-spacing:-0.02em; }}
  .hero .sub {{ color:var(--muted); font-size:0.95rem; margin-bottom:1.5rem; }}
  .hero .sub code {{ background:var(--card); padding:2px 7px; border-radius:4px; font-size:0.85rem; border:1px solid var(--border); }}
  .stats {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(140px,1fr)); gap:0.8rem; margin-top:1.2rem; }}
  .stat {{ background:var(--card); border:1px solid var(--border); border-radius:var(--radius); padding:1rem 1.2rem; text-align:center; transition:border-color .2s; }}
  .stat:hover {{ border-color:var(--accent); }}
  .stat .num {{ font-size:1.7rem; font-weight:700; color:var(--accent); line-height:1.2; }}
  .stat .label {{ font-size:0.72rem; color:var(--muted); text-transform:uppercase; letter-spacing:0.06em; margin-top:0.25rem; }}

  /* ── Nav ── */
  .nav {{ background:var(--surface); border-bottom:1px solid var(--border); padding:0 2rem; position:sticky; top:0; z-index:100; backdrop-filter:blur(12px); -webkit-backdrop-filter:blur(12px); }}
  .nav-inner {{ max-width:1100px; margin:0 auto; display:flex; gap:0; }}
  .nav a {{ font-size:0.82rem; color:var(--muted); padding:0.7rem 1rem; border-bottom:2px solid transparent; transition:all .15s; display:block; }}
  .nav a:hover {{ color:var(--text); text-decoration:none; }}
  .nav a.active {{ color:var(--accent); border-bottom-color:var(--accent); }}
  .nav .nav-right {{ margin-left:auto; display:flex; align-items:center; gap:0.8rem; }}
  .nav .nav-right a {{ font-size:0.78rem; color:var(--muted); }}
  .nav .nav-right a:hover {{ color:var(--accent2); }}

  /* ── Container ── */
  .container {{ max-width:1100px; margin:0 auto; padding:2.5rem 1.5rem; }}
  section {{ margin-bottom:3.5rem; scroll-margin-top:3.5rem; }}
  section h2 {{ font-size:1.3rem; font-weight:600; margin-bottom:1rem; padding-bottom:0.5rem; border-bottom:1px solid var(--border); display:flex; align-items:center; gap:0.5rem; }}
  section h2::before {{ content:''; width:4px; height:1.2em; background:var(--accent); border-radius:2px; flex-shrink:0; }}

  /* ── Class composition bar ── */
  .class-bar {{ display:flex; height:36px; border-radius:6px; overflow:hidden; margin:1rem 0; }}
  .class-bar div {{ display:flex; align-items:center; justify-content:center; font-size:0.72rem; font-weight:600; color:#fff; min-width:30px; transition:opacity .15s; }}
  .class-bar div:hover {{ opacity:.85; }}
  .legend {{ display:flex; gap:1.2rem; flex-wrap:wrap; margin:0.6rem 0 1.2rem; }}
  .legend span {{ display:flex; align-items:center; gap:0.4rem; font-size:0.8rem; color:var(--muted); }}
  .legend span::before {{ content:''; width:10px; height:10px; border-radius:3px; flex-shrink:0; }}
  .legend .l-ins::before {{ background:#6c72ff; }} .legend .l-con::before {{ background:#38bdf8; }}
  .legend .l-corr::before {{ background:#34d399; }} .legend .l-mrg::before {{ background:#fb923c; }}
  .legend .l-corp::before {{ background:#f472b6; }}

  /* ── Key findings ── */
  .findings {{ background:var(--surface); border:1px solid var(--border); border-radius:var(--radius); padding:1.2rem 1.5rem; margin-top:1rem; }}
  .findings h3 {{ font-size:0.9rem; font-weight:600; color:var(--accent2); margin-bottom:0.6rem; }}
  .findings ul {{ padding-left:1.2rem; color:var(--muted); font-size:0.88rem; }}
  .findings li {{ margin:0.3rem 0; }}
  .findings strong {{ color:var(--accent); }}

  /* ── Interactive grid ── */
  .interactive-grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(420px,1fr)); gap:1.2rem; }}
  .interactive-card {{ background:var(--card); border:1px solid var(--border); border-radius:var(--radius); overflow:hidden; transition:border-color .2s, box-shadow .2s; }}
  .interactive-card:hover {{ border-color:var(--accent); box-shadow:0 4px 20px rgba(108,114,255,.1); }}
  .interactive-card iframe {{ width:100%; height:420px; border:none; display:block; }}
  .interactive-card .ic-caption {{ padding:0.6rem 1rem; font-size:0.8rem; color:var(--muted); border-top:1px solid var(--border); }}

  /* ── Gallery ── */
  .gallery {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); gap:1rem; }}
  .gallery-item {{ background:var(--card); border:1px solid var(--border); border-radius:var(--radius); overflow:hidden; transition:transform .15s, box-shadow .15s; cursor:pointer; }}
  .gallery-item:hover {{ transform:translateY(-3px); box-shadow:0 8px 24px rgba(0,0,0,.4); }}
  .gallery-item img {{ width:100%; height:180px; object-fit:cover; display:block; background:#181b27; }}
  .gallery-item .caption {{ padding:0.5rem 0.8rem; font-size:0.75rem; color:var(--muted); border-top:1px solid var(--border); }}

  /* ── Tables grid ── */
  .tables-grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:0.8rem; }}
  .table-card {{ background:var(--card); border:1px solid var(--border); border-radius:var(--radius); padding:0.9rem 1.2rem; display:flex; align-items:center; gap:0.8rem; transition:border-color .15s; text-decoration:none; color:var(--text); }}
  .table-card:hover {{ border-color:var(--accent); text-decoration:none; }}
  .table-card .icon {{ font-size:1.4rem; flex-shrink:0; }}
  .table-card .info .name {{ font-weight:500; font-size:0.88rem; }}
  .table-card .info .desc {{ font-size:0.73rem; color:var(--muted); margin-top:0.1rem; }}

  /* ── Report markdown ── */
  .report-md {{ background:var(--card); border:1px solid var(--border); border-radius:var(--radius); padding:2rem; line-height:1.8; }}
  .report-md h1 {{ font-size:1.5rem; margin-bottom:0.5rem; }}
  .report-md h2 {{ font-size:1.15rem; color:var(--accent2); margin:1.5rem 0 0.5rem; }}
  .report-md h3 {{ font-size:1rem; color:var(--accent3); margin:1rem 0 0.3rem; }}
  .report-md table {{ border-collapse:collapse; width:100%; margin:0.8rem 0; font-size:0.85rem; }}
  .report-md th, .report-md td {{ border:1px solid var(--border); padding:0.4rem 0.7rem; text-align:left; }}
  .report-md th {{ background:var(--surface); color:var(--muted); font-weight:500; }}
  .report-md code {{ background:var(--surface); padding:1px 5px; border-radius:3px; font-size:0.82rem; }}
  .report-md pre {{ background:var(--surface); border:1px solid var(--border); border-radius:6px; padding:1rem; overflow-x:auto; margin:0.8rem 0; }}
  .report-md pre code {{ background:none; padding:0; }}
  .report-md blockquote {{ border-left:3px solid var(--accent); padding:0.5rem 1rem; margin:0.8rem 0; color:var(--muted); background:var(--surface); border-radius:0 6px 6px 0; }}
  .report-md strong {{ color:var(--accent); }}
  .report-md em {{ color:var(--muted); }}
  .report-md ul, .report-md ol {{ padding-left:1.5rem; margin:0.4rem 0; }}
  .report-md li {{ margin:0.2rem 0; }}

  /* ── Lightbox ── */
  .lightbox {{ display:none; position:fixed; inset:0; background:rgba(0,0,0,.92); z-index:1000; align-items:center; justify-content:center; cursor:zoom-out; }}
  .lightbox.active {{ display:flex; }}
  .lightbox img {{ max-width:92vw; max-height:92vh; border-radius:8px; box-shadow:0 0 60px rgba(0,0,0,.5); }}
  .lightbox .close {{ position:absolute; top:1.5rem; right:1.5rem; color:#fff; font-size:1.5rem; cursor:pointer; background:rgba(255,255,255,.1); width:44px; height:44px; border-radius:50%; display:flex; align-items:center; justify-content:center; transition:background .15s; }}
  .lightbox .close:hover {{ background:rgba(255,255,255,.2); }}
  .lightbox .caption-bar {{ position:absolute; bottom:2rem; left:50%; transform:translateX(-50%); background:rgba(0,0,0,.7); padding:0.5rem 1.2rem; border-radius:8px; font-size:0.85rem; color:#fff; backdrop-filter:blur(8px); max-width:80vw; text-align:center; }}

  /* ── Scroll to top ── */
  .scroll-top {{ position:fixed; bottom:2rem; right:2rem; width:44px; height:44px; border-radius:50%; background:var(--accent); color:#fff; border:none; cursor:pointer; font-size:1.2rem; display:flex; align-items:center; justify-content:center; opacity:0; pointer-events:none; transition:opacity .2s, transform .2s; z-index:999; box-shadow:0 4px 16px rgba(108,114,255,.3); }}
  .scroll-top.visible {{ opacity:1; pointer-events:auto; }}
  .scroll-top:hover {{ transform:translateY(-2px); }}

  /* ── Footer ── */
  footer {{ border-top:1px solid var(--border); padding:2rem; text-align:center; }}
  footer p {{ color:var(--muted); font-size:0.8rem; }}
  footer .sibling-links {{ margin-top:0.8rem; display:flex; gap:1.5rem; justify-content:center; flex-wrap:wrap; }}
  footer .sibling-links a {{ font-size:0.82rem; }}

  /* ── Responsive ── */
  @media (max-width:768px) {{
    .hero h1 {{ font-size:1.6rem; }}
    .stats {{ grid-template-columns:repeat(3,1fr); }}
    .interactive-grid {{ grid-template-columns:1fr; }}
    .gallery {{ grid-template-columns:repeat(auto-fill,minmax(200px,1fr)); }}
    .nav-inner {{ overflow-x:auto; }}
    .nav .nav-right {{ display:none; }}
  }}
</style>
</head>
<body>

<div class="hero">
  <div class="hero-inner">
    <h1>mailroom-dataset Corpus</h1>
    <div class="sub">EDA Dashboard &mdash; Generated <code>{generated}</code> &middot; Pipeline <code>run_all.py</code> (P0&ndash;P6) &middot; Data <code>Lucius-Morningstar/mailroom-dataset</code> v1 (corpus v9)</div>
    <div class="stats">
{chr(10).join(f'      <div class="stat"><div class="num">{n}</div><div class="label">{l}</div></div>' for l, n in stats)}
    </div>
  </div>
</div>

<div class="nav">
  <div class="nav-inner">
    <a href="#overview" class="active">Overview</a>
    <a href="#interactive">Interactive Charts</a>
    <a href="#gallery">Figures</a>
    <a href="#tables">Tables</a>
    <a href="#report">Full Report</a>
    <div class="nav-right">
      <a href="https://exios66.github.io/claims-data-eda/">Claims EDA</a>
      <a href="https://exios66.github.io/Enron-Evaluation-Environment/">Enron EDA</a>
    </div>
  </div>
</div>

<div class="container">

<section id="overview">
  <h2>Corpus Composition</h2>
  <div class="class-bar">
{bar}
  </div>
  <div class="legend">
{legend}
  </div>
  <div class="findings">
    <h3>Key Findings</h3>
    <ul>
{findings_html}
    </ul>
  </div>
</section>

<section id="interactive">
  <h2>Interactive Charts</h2>
  <div class="interactive-grid">
{interactive}
  </div>
</section>

<section id="gallery">
  <h2>All Figures ({len(figs)})</h2>
  <div class="gallery" id="gallery-grid">
{gallery}
  </div>
</section>

<section id="tables">
  <h2>Data Tables ({len(tables)})</h2>
  <div class="tables-grid">
{table_cards}
  </div>
</section>

<section id="report">
  <h2>Full Summary Report</h2>
  <div class="report-md" id="report-content">Loading...</div>
</section>

</div>

<footer>
  <p>mailroom-dataset Corpus EDA &mdash; Generated by <code>run_all.py</code> (P0&ndash;P6) &mdash; <a href="https://github.com/Exios66/Mailroom-Corpus-EDA">Source</a></p>
  <div class="sibling-links">
    <a href="https://exios66.github.io/claims-data-eda/">Claims EDA &rarr;</a>
    <a href="https://exios66.github.io/Enron-Evaluation-Environment/">Enron EDA &rarr;</a>
  </div>
</footer>

<div class="lightbox" id="lightbox" onclick="closeLightbox()">
  <div class="close">&times;</div>
  <img id="lightbox-img" src="" alt="">
  <div class="caption-bar" id="lightbox-caption"></div>
</div>

<button class="scroll-top" id="scrollTop" onclick="window.scrollTo({{top:0,behavior:'smooth'}})" aria-label="Scroll to top">&uarr;</button>

<script>
/* ── Lightbox ── */
function openLightbox(el) {{
  const img = el.querySelector('img');
  const cap = el.querySelector('.caption');
  document.getElementById('lightbox-img').src = img.src;
  document.getElementById('lightbox-caption').textContent = cap ? cap.textContent : '';
  document.getElementById('lightbox').classList.add('active');
}}
function closeLightbox() {{ document.getElementById('lightbox').classList.remove('active'); }}
document.addEventListener('keydown', e => {{ if (e.key === 'Escape') closeLightbox(); }});

/* ── Render markdown ── */
function renderMd(url, elId) {{
  fetch(url).then(r => r.text()).then(md => {{
    let html = md
      .replace(/```(\\w*)\\n([\\s\\S]*?)```/g, '<pre><code>$2</code></pre>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/^>\\s?(.+)$/gm, '<blockquote>$1</blockquote>')
      .replace(/<\\/blockquote>\\s*<blockquote>/g, '<br>')
      .replace(/\\|(.+)\\|/g, (m) => {{
        const cells = m.split('|').filter(c => c.trim());
        if (cells.every(c => /^[\\s\\-:]+$/.test(c))) return '';
        return '<tr>' + cells.map(c => `<td>${{c.trim()}}</td>`).join('') + '</tr>';
      }})
      .replace(/(<tr>[\\s\\S]*?<\\/tr>)/g, '<table>$1</table>')
      .replace(/<\\/table>\\s*<table>/g, '')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>[\\s\\S]*?<\\/li>)/g, (m) => {{ return m.includes('</ul>') ? m : '<ul>' + m + '</ul>'; }})
      .replace(/<\\/ul>\\s*<ul>/g, '')
      .replace(/\\n{{2,}}/g, '</p><p>')
      .replace(/\\n/g, '<br>');
    document.getElementById(elId).innerHTML = '<p>' + html + '</p>';
  }}).catch(() => {{
    document.getElementById(elId).innerHTML = '<p><a href="' + url + '">View raw markdown</a></p>';
  }});
}}
renderMd('SUMMARY_REPORT.md', 'report-content');

/* ── Smooth scroll ── */
document.querySelectorAll('.nav a[href^="#"]').forEach(a => {{
  a.addEventListener('click', e => {{
    e.preventDefault();
    const target = document.querySelector(a.getAttribute('href'));
    if (target) target.scrollIntoView({{ behavior:'smooth', block:'start' }});
  }});
}});

/* ── Scroll spy ── */
const sections = document.querySelectorAll('section[id]');
const navLinks = document.querySelectorAll('.nav a[href^="#"]');
const observer = new IntersectionObserver(entries => {{
  entries.forEach(entry => {{
    if (entry.isIntersecting) {{
      navLinks.forEach(l => l.classList.remove('active'));
      const active = document.querySelector(`.nav a[href="#${{entry.target.id}}"]`);
      if (active) active.classList.add('active');
    }}
  }});
}}, {{ rootMargin: '-20% 0px -70% 0px' }});
sections.forEach(s => observer.observe(s));

/* ── Scroll to top ── */
const scrollBtn = document.getElementById('scrollTop');
window.addEventListener('scroll', () => {{
  scrollBtn.classList.toggle('visible', window.scrollY > 400);
}});
</script>
</body>
</html>
"""


def main() -> int:
    summary = load_summary()
    html = build_index_html(summary)
    out = REPORT_DIR / "index.html"
    out.write_text(html)
    print(f"index.html regenerated -> {out} ({len(html)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())