"""Copy family manifest + prompt snapshots into another package checkout."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from mailroom_sandbox.paths import repo_root
from mailroom_sandbox.subagents.family import (
    family_roster_path,
    load_family_document,
    normalize_package_id,
    package_roster_dest,
)
from mailroom_sandbox.subagents.roster import load_roster


@dataclass
class MaterializeResult:
    family_roster_written: Path | None
    prompts_copied: list[Path]
    package: str


def _canonical_prompt_store(source_root: Path | None = None) -> Path:
    return (source_root or repo_root()) / ".opencode" / "agents"


def materialize_package(
    package: str,
    *,
    dest_root: Path,
    source_root: Path | None = None,
    dry_run: bool = False,
) -> MaterializeResult:
    """Install family-roster.yaml and missing OpenCode prompts for *package*."""
    package = normalize_package_id(package)
    src_root = source_root or repo_root()
    family_src = family_roster_path(src_root)
    if not family_src.is_file():
        raise FileNotFoundError(family_src)

    dest_family = package_roster_dest(package, dest_root, source_root=src_root)
    copied: list[Path] = []

    framework_src = src_root / "config" / "subagents" / "AGENT_FRAMEWORK.md"
    if not dry_run:
        dest_family.parent.mkdir(parents=True, exist_ok=True)
        if family_src.resolve() != dest_family.resolve():
            shutil.copy2(family_src, dest_family)
        if framework_src.is_file():
            shutil.copy2(framework_src, dest_family.parent / "AGENT_FRAMEWORK.md")

    # Package pointer roster (loader reads family file from dest)
    pointer = dest_root / "config" / "subagents" / "roster.yaml"
    pointer_body = (
        f"# Generated by sandbox subagents materialize\n"
        f"version: 1\n"
        f"package: {package}\n"
        f"extends: family-roster.yaml\n"
    )
    if package == "digital-mailroom":
        pointer = dest_root / "config" / "subagents" / "roster.yaml"
    if not dry_run:
        pointer.parent.mkdir(parents=True, exist_ok=True)
        pointer.write_text(pointer_body, encoding="utf-8")

    doc = load_family_document(src_root)
    store = _canonical_prompt_store(src_root)
    for row in doc.get("subagents") or []:
        if package not in (row.get("packages") or []):
            continue
        agent_id = row["id"]
        dest_prompt = dest_root / ".opencode" / "agents" / f"{agent_id}.md"
        if dest_prompt.is_file():
            continue
        src_prompt = store / f"{agent_id}.md"
        if not src_prompt.is_file():
            continue
        if not dry_run:
            dest_prompt.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_prompt, dest_prompt)
        copied.append(dest_prompt)

    written = dest_family if not dry_run else dest_family
    return MaterializeResult(
        family_roster_written=written,
        prompts_copied=copied,
        package=package,
    )
