#!/usr/bin/env python3
"""Compliance-specialist removal guard (DMR-064 unit).

Cements commit 59c47401 ("Finalize five-class taxonomy; remove docclass
arm"): the docclass-era compliance specialist must never reappear in the
monorepo — not as tracked paths, not as tokens in the llm-mailroom
source/docs surface, and not as a taxonomy class. A future subtree pull that
re-imports the upstream's pre-removal files (or anyone recreating the
tokens) must fail LOUDLY here.

Hermetic: stdlib unittest only, no network, read-only (no `status
--porcelain` semantics, no writes). Mirrors scripts/tests/test_sync_packages.py
conventions: subprocess with timeout=60, GIT_TERMINAL_PROMPT=0 env.

Run:  python3 -m unittest discover scripts/tests -v
"""

import os
import re
import subprocess
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# The five tracked paths 59c47401 deleted. Absence is asserted at the
# git-TRACKING level (`git ls-files`), which catches a subtree-pull
# re-import even if the working tree was scrubbed afterwards.
FORBIDDEN_TRACKED_PATHS = (
    "packages/llm-mailroom/src/agents/compliance_specialist.py",
    "packages/llm-mailroom/src/langchain_agents/prompts_docclass.py",
    "packages/llm-mailroom/src/langchain_agents/skills/compliance_specialist/README.md",
    "packages/llm-mailroom/src/langchain_agents/skills/compliance_specialist/filing-types.md",
    "packages/llm-mailroom/src/pipeline/docclass_mode.py",
)

# The five docclass-era tokens. Case-insensitive word-ish substring match —
# legal-prose "compliance" (e.g. the CUAD "Compliance with Covenant Closing
# Condition" clause text in src/langchain_agents/cuad_maud.py, fixture prose)
# must NOT trip the guard; only these exact tokens do.
TOKEN_RE = re.compile(
    r"\b(?:compliance_specialist|compliance_filing|docclass_mode|"
    r"prompts_docclass|filing-types)\b",
    re.IGNORECASE,
)

# Explicit scan surface — NEVER the whole repo. In particular the sandbox
# vendor snapshot (packages/local-mailroom-sandbox/vendor/**) is deliberately
# EXCLUDED: it is a pinned pre-removal snapshot and a separate DMR-057
# concern. Keep these lists explicit; do not broaden the globs.
SRC_SCAN_ROOT = REPO_ROOT / "packages" / "llm-mailroom" / "src"
SRC_SUFFIXES = (".py", ".yaml", ".md", ".txt")
EXTRA_SCAN_FILES = (
    REPO_ROOT / "packages/llm-mailroom/notebooks/pipeline_lab.py",
    REPO_ROOT / "packages/llm-mailroom/notebooks/_build_extension_notebooks.py",
    REPO_ROOT / "packages/llm-mailroom/docs/agents.md",
    REPO_ROOT / "packages/llm-mailroom/docs/local-models.md",
    REPO_ROOT / "packages/llm-mailroom/docs/testing.md",
)

TAXONOMY = REPO_ROOT / "packages/llm-mailroom/src/config/taxonomy.yaml"
EXPECTED_DOC_CLASSES = {
    "contract", "merger_agreement", "corporate_record",
    "correspondence", "insurance_claim",
}


def _git_env():
    env = dict(os.environ)
    env["GIT_TERMINAL_PROMPT"] = "0"
    return env


def _read_text(path):
    return path.read_text(encoding="utf-8", errors="replace")


def _ls_files():
    res = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files"],
        cwd=str(REPO_ROOT), env=_git_env(), capture_output=True,
        text=True, timeout=60,
    )
    res.check_returncode()
    return set(res.stdout.splitlines())


def _scan_text(text):
    """Return (line_no, line) pairs where a docclass token occurs."""
    hits = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        if TOKEN_RE.search(line):
            hits.append((line_no, line))
    return hits


def _fmt_hits(hits):
    return "\n".join(f"  {path}:{ln}: {line.strip()}"
                     for path, ln, line in hits)


class TestComplianceRemovalGuard(unittest.TestCase):
    def test_docclass_arm_fully_removed(self):
        # 1) git-tracking-level absence (the critical check): none of the
        # deleted paths may exist in `git ls-files` for the monorepo.
        with self.subTest("tracked paths absent from git ls-files"):
            tracked = _ls_files()
            present = [p for p in FORBIDDEN_TRACKED_PATHS if p in tracked]
            self.assertEqual(
                present, [],
                "docclass-era paths re-added to git tracking: "
                + ", ".join(present))

        # 2) token scan — src surface (working-tree level). Generated
        # `*.egg-info/` build artifacts are skipped: they are gitignored,
        # regenerated by `pip install -e .`, and a stale local egg-info
        # (e.g. an old SOURCES.txt from before 59c47401) is not repo content —
        # tripping the guard on it would only report stale local build state.
        with self.subTest("no docclass tokens in src surface"):
            src_hits = []
            for path in sorted(SRC_SCAN_ROOT.rglob("*")):
                if any(part.endswith(".egg-info") for part in path.parts):
                    continue
                if path.is_file() and path.suffix in SRC_SUFFIXES:
                    src_hits.extend(
                        (str(path.relative_to(REPO_ROOT)), ln, line)
                        for ln, line in _scan_text(_read_text(path)))
            self.assertEqual(src_hits, [],
                             "docclass tokens found in src surface:\n"
                             + _fmt_hits(src_hits))

        # 3) token scan — the notebooks + docs pinned by the auditor.
        with self.subTest("no docclass tokens in notebooks/docs"):
            extra_hits = []
            for path in EXTRA_SCAN_FILES:
                if not path.is_file():
                    extra_hits.append(
                        (str(path.relative_to(REPO_ROOT)), 0, "<missing>"))
                    continue
                extra_hits.extend(
                    (str(path.relative_to(REPO_ROOT)), ln, line)
                    for ln, line in _scan_text(_read_text(path)))
            self.assertEqual(extra_hits, [],
                             "docclass tokens found in notebooks/docs:\n"
                             + _fmt_hits(extra_hits))

        # 4) taxonomy contract: exactly the five live classes, no
        # compliance_filing/compliance_specialist, no retired status.
        with self.subTest("taxonomy doc_classes contract"):
            tax = _read_text(TAXONOMY)
            lines = tax.splitlines()
            start = next(i for i, l in enumerate(lines)
                         if l.startswith("doc_classes:"))
            end = next((i for i in range(start + 1, len(lines))
                        if lines[i] and not lines[i][0].isspace()
                        and not lines[i].startswith("#")), len(lines))
            section = "\n".join(lines[start + 1:end])
            keys = set(re.findall(r"key:\s*([a-z_]+)", section))
            self.assertEqual(
                keys, EXPECTED_DOC_CLASSES,
                "doc_classes keys drifted from the five-class taxonomy")
            self.assertNotIn(
                "compliance", section.lower(),
                "doc_classes section still references compliance_filing")
            self.assertNotIn(
                "status: retired", tax.lower(),
                "taxonomy.yaml still carries a retired status")

        # 5) scan-surface hygiene: the guard never scans the whole repo —
        # the sandbox vendor snapshot stays out of scope by construction.
        with self.subTest("scan surface explicit and excludes vendor"):
            surface = str(SRC_SCAN_ROOT) + "".join(map(str, EXTRA_SCAN_FILES))
            self.assertNotIn(
                "local-mailroom-sandbox", surface,
                "vendor snapshot leaked into the scan surface")


if __name__ == "__main__":
    unittest.main()
