"""SAND-032: render the deploy env a run YAML implies, and diff it vs a shell.

``deploy/modal_vllm.py`` reads ``MODAL_VLLM_*`` at import time, but the run
YAML is the source of truth. ``spec_env`` is the single mapping,
``env_drift`` is the loud check benchmark-check runs, and ``render_exports``
is what the operator sources before ``modal deploy``. No credentials are
ever rendered (the API token and HF token stay out of this module).
"""

from __future__ import annotations

import json
from typing import Mapping

from mailroom_sandbox.job.runbooks import _shell_quote
from mailroom_sandbox.job.spec import RunSpec


_DEPLOY_DEFAULT_KEYS = (
    "MODAL_VLLM_TP_SIZE",
    "MODAL_VLLM_ATTENTION_BACKEND",
    "MODAL_VLLM_ASYNC_SCHEDULING",
    "MODAL_VLLM_REASONING_PARSER",
    "MODAL_VLLM_REASONING_PARSER_PLUGIN",
    "MODAL_VLLM_TOOL_CALL_PARSER",
    "MODAL_VLLM_ENABLE_AUTO_TOOL_CHOICE",
    "MODAL_VLLM_STARTUP_TIMEOUT_SECONDS",
    "MODAL_VLLM_CHAT_TEMPLATE",
)


def _b(value: bool) -> str:
    return "1" if value else "0"


def spec_env(spec: RunSpec) -> dict[str, str]:
    """Every deploy knob the spec pins, as the exact env string modal_vllm reads."""
    v = spec.engine.vllm
    m = spec.engine.modal
    kwargs = "" if v.enable_thinking is None else json.dumps({"enable_thinking": v.enable_thinking})
    env = {
        "MODAL_VLLM_MODEL": spec.engine.model,
        "MODAL_VLLM_MAX_MODEL_LEN": str(v.max_model_len),
        "MODAL_VLLM_GPU_MEMORY_UTILIZATION": f"{v.gpu_memory_utilization:.2f}",
        "MODAL_VLLM_MAX_NUM_SEQS": str(v.max_num_seqs),
        "MODAL_VLLM_ENABLE_PREFIX_CACHING": _b(v.enable_prefix_caching),
        "MODAL_VLLM_ENFORCE_EAGER": _b(v.enforce_eager),
        "MODAL_VLLM_QUANTIZATION": v.quantization,
        "MODAL_VLLM_REVISION": v.revision,
        "MODAL_VLLM_KV_CACHE_DTYPE": v.kv_cache_dtype,
        "MODAL_VLLM_DEFAULT_CHAT_TEMPLATE_KWARGS": kwargs,
        "MODAL_VLLM_CUDAGRAPH_CAPTURE_SIZES": ",".join(str(x) for x in v.cudagraph_capture_sizes),
        "MODAL_VLLM_MAX_NUM_BATCHED_TOKENS": (
            "" if v.max_num_batched_tokens is None else str(v.max_num_batched_tokens)
        ),
        "MODAL_VLLM_MAX_INPUTS": str(v.max_inputs) if v.max_inputs else "",
        "MODAL_VLLM_HF_OVERRIDES": json.dumps(v.hf_overrides, sort_keys=True) if v.hf_overrides else "",
        # Knobs the deploy reads that no SAND-032 run sets: pinned to "unset"
        # (deploy default) so a stale shell — e.g. the Granite runbook's
        # MODAL_VLLM_REASONING_PARSER=granite — is caught as drift and cleared
        # by sourcing render_exports. Parity with deploy/modal_vllm.py is
        # enforced by test_spec_env_covers_every_key_the_deploy_reads.
        **{key: "" for key in _DEPLOY_DEFAULT_KEYS},
    }
    if m is not None:
        env.update(
            {
                "MODAL_VLLM_APP_NAME": "" if m.app == "sandbox-vllm" else m.app,
                "MODAL_VLLM_GPU": m.gpu,
                "MODAL_VLLM_IMAGE_TAG": m.image_tag,
                "MODAL_VLLM_MAX_CONTAINERS": str(m.max_containers),
                "MODAL_VLLM_MIN_CONTAINERS": str(m.min_containers),
                "MODAL_VLLM_SCALEDOWN_SECONDS": str(m.scaledown_seconds),
            }
        )
    return env


def env_drift(spec: RunSpec, environ: Mapping[str, str]) -> list[str]:
    """One message per key whose shell value differs from the spec (unset == "")."""
    out: list[str] = []
    for key, want in spec_env(spec).items():
        have = (environ.get(key) or "").strip()
        if have != want:
            out.append(f"{key}: shell has {have!r}, run YAML wants {want!r}")
    return out


def render_exports(spec: RunSpec) -> str:
    lines = [f"# deploy env for {spec.run_id} (generated by `sandbox run deploy-env`)"]
    for key, val in spec_env(spec).items():
        # "" means deploy default: unset it (an exported "" breaks int() knobs).
        lines.append(f"unset {key}" if val == "" else f"export {key}={_shell_quote(val)}")
    return "\n".join(lines) + "\n"
